### ISSUE TITLE
Flow control settings

### ISSUE THREAD

**Issue by overhome1** [tdhoward/COMpipe#4]
I have been using your program to pipe a usb com port to a hyper-v Win XP Virtual Machine. It works great for a terminal program. However, I run some programs that are sensitive to the flow control (i.e. Xon/Xoff, Hardware, or None). Normally, these programs operate at 9600-8-N-1 and I don't give flow control much thought except when they (rarely) freeze. These programs work for a few seconds and then freeze using your pipe.  There is no binary data being transferred, so that shouldn't be an issue.  Is there anyway to adjust flow control? I have tried adjusting the flow control on both the guest and the host machine with a varying amount of success.
Thanks.

**Comment by tdhoward** [comment]
Hmm.  I've never used a device or software that required flow control, so I don't have any experience with this.  What is your full chain of devices and software?  Maybe we can figure out what is happening.

**Comment by overhome1** [comment]
Flow control is just a guess on my part.  
The software is from multple vendors and the software actually runs a hidden terminal session in the background.  By that, I mean, the software still transmits across a rs232 terminal session and interprets the response back from equipment in a ghosted terminal session to give a response back to the user.  Each software is for convenience for the user only.  A plain terminal can be used and it works well with the COMpipe software. However, when I try to run the vendor software it hangs up, then I force the software to close, then again open a terminal and continue from where the software session stopped.
It is very similar in concept to the old Win95 or 98 running on top of DOS.  
So the chain of devices and software is the same as a normal terminal session running from the guest VM, to VM com port, to the Hyper-V pipe, to COMpipe, to host machine physical rs232 com port.  All I am trying to do in essence is run a vendor specific software on top of the terminal session in the guest VM.  
Like I said the flow control is a guess on my part.  Or maybe the buffer is too small on COMpipe?

**Comment by villivateur** [comment]
@tdhoward  This issue should be reopened. Flow control is useful when program MCUs. For example, flashing ESP32 boards automatically, without pressing the reset button.

**Comment by tdhoward** [comment]
@villivateur Sure, flow control would be a good thing.  Hardware control is out of the question, though, since named pipes cannot transfer the CTS/RTS signals.  That leaves software-based flow control (XON/XOFF) as the only remaining approach.  Theoretically, this should already work (I think), since the bytes for XON and XOFF are being transferred via the named pipe.

I do not have any hardware on hand that uses XON/XOFF flow control, so if you do, I would appreciate any help with testing.  Otherwise, since I don't have solid reports of software-based flow control not working, I'll likely close this issue after a few months unless I hear differently.

**Comment by tdhoward** [comment]
It's been a few months now, and since there are no further reports of issues with software-based flow control, I'm going to close this issue.
